### ISSUE TITLE
Generated documentation file should contain version of k8s

### ISSUE THREAD

**Issue by bmillemathias-1a** [tha2015/kubernetes-doc-epub#1]
Hello,

first, thanks for creating the project and also sharing the files.
Could it be possible to have the version of k8s the documentation applies on. Perhaps for last 5 supported versions a directory named based on the version (1.17, 1.16, ...) and put each file inside ?

Thanks

**Comment by tha2015** [comment]
Thanks for the first issue :)
I will create folders and generate files for 1.18 soon

**Comment by tha2015** [comment]
The ebooks for 1.17 and 1.18 are now put in separate folders https://github.com/tha2015/kubernetes-doc-epub
